use_frameworks!

platform :ios, '15.0'

target 'MyUltronServer_Example' do
  pod 'MyUltronServer', :path => '../'

  target 'MyUltronServer_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
